# Generated by Django 2.1.3 on 2018-11-12 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lenguajes',
            fields=[
                ('id_lenguaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lenguaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tema', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('id_lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Lenguajes')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='id_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Temas'),
        ),
    ]
